/*
 * The app's theme — the successor to styles.xml + colors.xml.
 *
 * Wrapping the UI in MaterialTheme makes a ColorScheme, a Typography set and a Shape set
 * available to every composable underneath it, via MaterialTheme.colorScheme / .typography
 * (that's how the cards and text in RotatorlatorScreens pick up their colours without a
 * single hardcoded hex). It's the same idea as an XML theme, except it's a plain function
 * call and the values are read in Kotlin instead of resolved through attribute lookups.
 */

package com.justbnutz.dockorientationrotatorlator.ui

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext

/**
 * Material You: the colour scheme is generated by the system from the user's wallpaper,
 * so the app matches the rest of their device instead of imposing the old teal/amber.
 *
 * Dynamic colour needs API 31+, which is exactly this app's minSdk — so there's no static
 * fallback scheme to maintain. (The 2018 teal survives in one place only: the splash
 * screen background, in colors.xml.)
 *
 * isSystemInDarkTheme() reads the system setting AND re-composes if it changes, so
 * flipping dark mode while the app is open just works — the app's first ever dark theme.
 */
@Composable
fun RotatorlatorTheme(content: @Composable () -> Unit) {

    val context = LocalContext.current

    val colorScheme = if (isSystemInDarkTheme()) {
        dynamicDarkColorScheme(context)
    } else {
        dynamicLightColorScheme(context)
    }

    MaterialTheme(
        colorScheme = colorScheme,
        content = content
    )
}
